name: release process

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    name: Build macOS Binaries
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
          - target: aarch64-apple-darwin

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Build binary
      run: cargo build --release --target ${{ matrix.target }}

    - name: Create archive
      run: |
        mkdir -p dist
        cp target/${{ matrix.target }}/release/localports dist/
        tar -czf localports-${{ matrix.target }}.tar.gz -C dist localports

    - name: Generate SHA256
      run: |
        echo "SHA256 for ${{ matrix.target }}:"
        shasum -a 256 localports-${{ matrix.target }}.tar.gz

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: localports-${{ matrix.target }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
